name: dio_clean_http_response
description: "Dio extension for cleaner HTTP response and error/exception handling through functional programming (Either type pattern). All failures are covered using HttpFailure sealed class."
version: 2.0.0
repository: https://github.com/tpal-dev/dio_clean_http_response
homepage: https://github.com/tpal-dev/dio_clean_http_response

topics:
  - dio
  - http
  - error-handling
  - sealed-class
  - either-type

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
